version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: django_mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "django_db"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_PASSWORD: "admin"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
